# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json

gui:

  theme:
    activeBorderColor:
      - '#eba0ac'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'

  returnImmediately: true

logs:
  timestamps: false
  since: '' # '60m' # set to '' to show all logs
  tail: '' # set to 200 to show last 200 lines of logs
